apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-neo4j-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-neo4j-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-neo4j-logs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-neo4j-logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-neo4j-import
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-neo4j-import
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-neo4j-plugins
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-neo4j-plugins
