apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-neo4j-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.93.226.51
    path: /shared/neo4j_data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-neo4j-logs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.93.226.51
    path: /shared/neo4j_logs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-neo4j-import
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.93.226.51
    path: /shared/neo4j_import
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-neo4j-plugins
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.93.226.51
    path: /shared/neo4j_plugins
