apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-server-data
spec:
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: x.x.x.x   # Replace with your NFS server IP
    path: /shared/server_data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-server-data-env
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: x.x.x.x  # Replace with your NFS server IP
    path: /shared/server_env
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-server-data-static
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: x.x.x.x  # Replace with your NFS server IP
    path: /shared/server_static
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-server-data-labels
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: x.x.x.x  # Replace with your NFS server IP
    path: /shared/server_labels
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-tensorboard-logs
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: x.x.x.x  # Replace with your NFS server IP
    path: /shared/server_tensorboard